### ISSUE TITLE
Add information about the company or developers behind this plugin 

### ISSUE THREAD

**Issue by renatoathaydes** [gradle-webtools/gradle-minify-plugin#15]
Hi! First of all, thanks for creating this plugin, as you probably know Gradle didn't have a good plugin to work with web resources, and this plugin seems to finally cover that gap!

That said, given there are many poorly maintained projects in this area, and that some (like the one I used to use) have been abandoned for years (don't even work with Gradle 6.x and won't review/accept PRs fixing important things), it would be nice to know who is behind this plugin, and how committed you are to maintaining this plugin up-to-date and accepting/reviewing Pull Requests from external contributors.

Notice that I am not implying I expect you to do anything, I just wanted to know what your intentions are with this plugin so we can make an informed decision on whether or not to use and perhaps contribute to this project.

Best regards.

**Comment by timon-schelling** [comment]
Hi! First, thanks for reaching out, nice to hear that there is use for our plugin.
Regarding our personas there is not much to say, just two developers with some time to spare and a need to fill the gap you mentioned. If want to know anything specific feel free to ask.

I know maintenance is a huge problem for a lot of opensource projects. And after all this project could theoretically suffer from it. But I use it my self in multiple projects and therefor have an interest of keeping it alive. I will (if time permits) review/accept PRs and resolve issues. Feel free to share your ideas or contribute.

Best regards.

**Comment by renatoathaydes** [comment]
Cool... the first thing I noticed was that it doesn't support the Groovy Gradle DSL. I think that you just need to change the types you use for the blocks (i.e. not Kotlin functions, but things like Java's `Function` or `Runnable` so it's compatible with all JVM languages) to fix that, but I am not sure.

**Comment by 616slayer616** [comment]
We had problems with that too and were not sure how to resolve it.
Would you like to try your suggestion? Even if it doesn't work your input might help us find a solution.

Feel free to create and new Issue with a detailed description.

**Comment by 616slayer616** [comment]
I think you're talking about this issue:
https://github.com/gradle-webtools/gradle-minify-plugin/issues/7

**Comment by 616slayer616** [comment]
@renatoathaydes Could you help us fix this or point us in the right direction?
I don’t understand where you think the Function or Runnable  belongs.

**Comment by renatoathaydes** [comment]
I am on vacation. Will get back to you next week.

**Comment by 616slayer616** [comment]
I created a new issue for the problem:
https://github.com/gradle-webtools/gradle-minify-plugin/issues/22

Any help would be appreciated.
