### ISSUE TITLE
Update closure Compiler

### ISSUE THREAD

**Issue by 616slayer616** [gradle-webtools/gradle-minify-plugin#19]
Closure Compiler versions v20210202 and later have removed the "dartPass"-flag.
This is a breaking change.

**Comment by timon-schelling** [comment]
Should we move closure in this github org? (maybe also the gradle dependecy)

**Comment by 616slayer616** [comment]
I looked into it when we moved this repo.
But the release process is much more complicated to get it into the maven nexus.

**Comment by timon-schelling** [comment]
You release by hand? or with Jenkins?

**Comment by 616slayer616** [comment]
With Jenkins.
But that’s not the issue.

The annoying thing is to create an account here:
https://issues.sonatype.org/secure/Dashboard.jspa

get your stuff approved and then create GPG keys and use them correctly to deploy there.

**Comment by timon-schelling** [comment]
Why not upload to JCenter or another big free maven repo?

**Comment by 616slayer616** [comment]
I don’t know how the process is there.
Wouldn’t JCenter require us to add the repository definition in our build file?
