### ISSUE TITLE
Problems install plugin

### ISSUE THREAD

**Issue by ejocampos** [gradle-webtools/gradle-minify-plugin#21]
Hi, thanks for the plugin, it is very useful, but I have a problem, I follow your instructions and I get the following error: "Could not set unknown property 'srcDir' for extension 'minification' of type org.gradlewebtools.minify.MinifyPluginExtension."

My project is set as follows: 
- gradle 6.1.

```
buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "org.gradle-webtools.minify:gradle-minify-plugin:1.1.0"
    }
}

....


apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: "org.gradlewebtools.minify"



minification {
    js { //this: JsMinifyTask
        srcDir = file("/js")
        dstDir = file("build/js")
    }
    css { //this: CssMinifyTask
        srcDir = project.file("css")
        dstDir = project.file("build/css")
    }
}
```
[build.gradle.txt](https://github.com/gradle-webtools/gradle-minify-plugin/files/6763215/build.gradle.txt)

thanks very much

**Comment by 616slayer616** [comment]
Hi,
we are having problems with groovy configurations right now.
We were not able to fix the issue for configurations like yours yet.

As a workaround you can create new tasks like this:
https://github.com/gradle-webtools/gradle-minify-plugin/issues/7#issuecomment-727858198

I hop this helps.

Feel free to ask if you are still having problems
