### ISSUE TITLE
Problem of compatibility with Java Versions

### ISSUE THREAD

**Issue by douglasbandeiraivo** [gradle-webtools/gradle-minify-plugin#30]
Hi. I'm getting a problem of compatibility with Java Versions. My project Java version is 8 and the _gradle-minify-plugin_ apparently needs Java 11. Is there an workaround or the only solution is to upgrade Java version? 

The erros is:

> A problem occurred configuring project ':app'.
> > Could not resolve all artifacts for configuration ':app:classpath'.
>    > Could not resolve org.gradle-webtools.minify:gradle-minify-plugin:1.2.1.
>      Required by:
>          project :app > org.gradlewebtools.minify:org.gradlewebtools.minify.gradle.plugin:1.2.1
>       > No matching variant of org.gradle-webtools.minify:gradle-minify-plugin:1.2.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
>           - Variant 'apiElements' capability org.gradle-webtools.minify:gradle-minify-plugin:1.2.1 declares a library, packaged as a jar, and its dependencies declared externally:
>               - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
>           - Variant 'runtimeElements' capability org.gradle-webtools.minify:gradle-minify-plugin:1.2.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
>               - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Exception is:
> org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
> 
> Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all artifacts for configuration ':app:classpath'.
> 
> Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.gradle-webtools.minify:gradle-minify-plugin:1.2.1.
> Required by:
>     project :app > org.gradlewebtools.minify:org.gradlewebtools.minify.gradle.plugin:1.2.1
> Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of org.gradle-webtools.minify:gradle-minify-plugin:1.2.1 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
>   - Variant 'apiElements' capability org.gradle-webtools.minify:gradle-minify-plugin:1.2.1 declares a library, packaged as a jar, and its dependencies declared externally:
>       - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
>   - Variant 'runtimeElements' capability org.gradle-webtools.minify:gradle-minify-plugin:1.2.1 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
>       - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

**Comment by 616slayer616** [comment]
We cannot simply use JDK 8 in the github action because it is not compatible  with sonar.

It would be possible to build it again with JDK 8 though.

I don't know if this solves the problem.

Could you try it with version 1.2.3-SNAPSHOT ?

**Comment by douglasbandeiraivo** [comment]
> Could you try it with version 1.2.3-SNAPSHOT ?

@616slayer616, using the version _1.2.3-SNAPSHOT_ solved the problem. Thanks.

**Comment by 616slayer616** [comment]
Ok
I will create a new release 1.2.3 with this fix

**Comment by timon-schelling** [comment]
@616slayer616  Can that be a breaking change for anyone?

**Comment by 616slayer616** [comment]
I don't think so.
Backwards compatibility should be given
