### ISSUE TITLE
Unknown Properties for Options

### ISSUE THREAD

**Issue by richaplinvs** [gradle-webtools/gradle-minify-plugin#35]
Hi,

I am trying to get the output of the minification to be a single file (one for js and another for css). I was experimenting with the options to get this to work and get the following errors where the type cannot be resolved: 

```
task additionalJsMinify(type: org.gradlewebtools.minify.JsMinifyTask) {
    srcDir = project.file(myJsPath)
    dstDir = project.file(myJsPath)
    options.ignoreMinFiles = false
    options.angularPass = false
    options.compilationLevel = CompilationLevel.SIMPLE_OPTIMIZATIONS
}
```

`Could not get unknown property 'CompilationLevel' for task ':additionalJsMinify' of type org.gradlewebtools.minify.JsMinifyTask.`

```
task myCssMinify(type: org.gradlewebtools.minify.CssMinifyTask) {
    srcDir = project.file(myCssPath)
    dstDir = project.file(myCssPath)
    options.outputFormat = OutputFormat.COMPRESSED
}
```

`Could not get unknown property 'OutputFormat' for task ':myCssMinify' of type org.gradlewebtools.minify.CssMinifyTask.`

Am I missing an import or a namespace prefix?

Also, is it possible to specify a list of source files instead of a srcDir? I'd like to ensure the minification is done in a specific order.

I have this as the dependency:

```
plugins {
    id("org.gradlewebtools.minify") version "1.3.0"
}
```

Thanks.

**Comment by mahaadev** [comment]
Facing same issue, when setting CompilationLevel.
```
task minifyJs(type: org.gradlewebtools.minify.JsMinifyTask) {
	srcDir = project.file("src/main/resources/static/js")
	dstDir = project.file("build/tmp/js")
	options {
		compilationLevel = CompilationLevel.SIMPLE_OPTIMIZATIONS
		strictModeInput = false
		ignoreMinFiles = true
		originalFileNames = true
	}
}
```

```
What went wrong:
A problem occurred evaluating root project 'project_demo'.
Could not get unknown property 'CompilationLevel' for JsMinifierOptions(compilationLevel=SIMPLE_OPTIMIZATIONS, env=BROWSER, languageIn=null, languageOut=null, warningLevel=QUIET, extraAnnotationNames=[], strictModeInput=false, debug=false, exportLocalPropertyDefinitions=false, formatting=[], generateExports=false, renamePrefixNamespace=null, renameVariablePrefix=null, moduleResolution=BROWSER, processCommonJsModules=false, packageJsonEntryNames=[], angularPass=false, dartPass=false, forceInjectLibrary=[], polymerVersion=null, rewritePolyfills=false, charset=UTF-8, checksOnly=false, browserFeaturesetYear=null) of type org.gradlewebtools.minify.minifier.js.JsMinifierOptions.
```


OS: Ubuntu 20.04
Java: 16
Gradle : 7.1.1
Spring: 2.6 snapshot

**Comment by mahaadev** [comment]
@richaplinvs I have found a solution to this.

to minify JS with SIMPLE_OPTIMIZATIONS write  `com.google.javascript.jscomp.CompilationLevel.SIMPLE_OPTIMIZATIONS `instead of` CompilationLevel.SIMPLE_OPTIMIZATIONS`

```
 task minifyJs(type: org.gradlewebtools.minify.JsMinifyTask) {
 	srcDir = project.file("src/dir")
 	dstDir = project.file("build/tmp/js")
 	options {
 		warningLevel = com.google.javascript.jscomp.WarningLevel.VERBOSE
 		compilationLevel = com.google.javascript.jscomp.CompilationLevel.SIMPLE_OPTIMIZATIONS
 		debug = true
 		strictModeInput = false
 		ignoreMinFiles = true
 		originalFileNames = true
 	}
}
```
to compress CSS write  `com.google.common.css.JobDescription.OutputFormat.COMPRESSED ` instead of `OutputFormat.COMPRESSED`

```
task minifyCss(type: org.gradlewebtools.minify.CssMinifyTask) {
	srcDir = project.file("src/main/resources/static/css")
	dstDir = project.file("build/tmp/css")
	options {
		options.outputFormat = com.google.common.css.JobDescription.OutputFormat.COMPRESSED
		ignoreMinFiles = true
		originalFileNames = true
	}
}
```

you can close this issue if this resolves your problem.

**Comment by timon-schelling** [comment]
Hi, thanks for using the plugin.
Sorry for the late comment, and thanks @mahaadev for the quick solution.

For explanation, we have decided not to use custom types (and mapping those) for configuring the minify backends. These must be imported or revert to with their full name. But it is worth considering if this should be changed in version 2. Until then, it should at least be documented. I will create issue and pr as soon as possible.

@richaplinvs is your problem solved? I'm going to close this, if you still have problems comment here or if a different problem arises in a new issue.

**Comment by richaplinvs** [comment]
Hi,

Thanks for the responses and it's got me passed the error. It's not really answered my wider question though. Having played with the compilation levels I still can't get the minification to output a single file - is this possible? I'd also like to specify the order of files to be minified - not sure if this is possible either?

Thanks for the help.
