### ISSUE TITLE
Show warnings in js minify?

### ISSUE THREAD

**Issue by Mike-the-one** [gradle-webtools/gradle-minify-plugin#36]
Is there a way to show error or warning if I am using a variable without first define it?

For example the following code:

```js
a = "hello";
```

vs

```js
let a = "hello";
```

I am using the following options:

```sh
options.strictModeInput = true
options.ignoreMinFiles = true
options.warningLevel = "DEFAULT"
options.originalFileNames = true
```
It won't give me any warnings if I just use a variable without first define it, and the result minified js does not work in browser, give me this error `Uncaught ReferenceError: a is not defined`.

if I change to 
```sh
options.warningLevel = "VERBOSE"
```

Then the build fails with many errors, won't even recognize jquery `$` sign.  Tried with `options.compilationLevel = "SIMPLE_OPTIMIZATIONS"`, same errors.

Thanks

**Comment by 616slayer616** [comment]
When I try your snippet it results in `'use strict';a="hello";`.

The added `use strinct` is what makes your code fail in browser.

This can be controlled by the emitUseStrict flag.
We will have to add that and make a release soon.


For the problems with activated VERBOSE mode you will probably have to get help from the closure compiler team itself.

**Comment by Mike-the-one** [comment]
@616slayer616 thank you so much!!!
