### ISSUE TITLE
maven repo update?

### ISSUE THREAD

**Issue by Mike-the-one** [gradle-webtools/gradle-minify-plugin#42]
Thanks for this great tool!  I am wondering is it possible to update maven repo to the latest version?  Current version on Maven is 1.23, and the latest is 1.3.1

Thanks

**Comment by 616slayer616** [comment]
I guess you mean here?:
https://mvnrepository.com/artifact/org.gradle-webtools.minify/gradle-minify-plugin

We don't control that.
I have no idea how it landed there.
We only publish to the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/org.gradlewebtools.minify)

**Comment by timon-schelling** [comment]
Add `https://plugins.gradle.org/m2/` as a maven repo if you want to use it elsewhere.
`org.gradle-webtools.minify:gradle-minify-plugin:1.3.1` should now resolve.

@Mike-the-one
