### ISSUE TITLE
JsMinifyTask reports outdated warnings

### ISSUE THREAD

**Issue by 4braincells** [gradle-webtools/gradle-minify-plugin#49]
JsMinifyTask still reports outdated warnings

`Warning: Custom property reference encountered. Please note that custom properties do not work with all major browsers, and their use is discouraged. at xyz.css line 40:742
`

As of 2017, all major browsers support custom properties.

**Comment by timon-schelling** [comment]
@616slayer616 can we disable this in the backend

**Comment by 616slayer616** [comment]
I don't think it makes sense to filter the messages from the backend.
But if this is really obsolete then the newer versions should not contain this warning anymore.
We already have a PR to upgrade the closure compiler but it is quite old.
So I updated the dependencies again and am working on getting the build to run so I would suggest to release this:
https://github.com/gradle-webtools/gradle-minify-plugin/pull/48

**Comment by timon-schelling** [comment]
@4braincells thx for reporting :)

**Comment by 4braincells** [comment]
Thanks for reacting so fast :-)
I was ready for a RELEASE after a long time, I stumbled upon it by chance ... 

Just saw the 2.0.0 already on org.gradlewebtools.minify
Is there a special reason why it depends on JVM 19?
As I am using Java LTS versions (and still on 17) , I wont be able to switch until 21.

**Comment by 616slayer616** [comment]
I needed to upgrade the jdk because of the new Gradle version.
But I will check if 17 or even earlier also works

**Comment by 616slayer616** [comment]
Ok I released again with JDK 17.
Lower was not possible because of sonarqube

**Comment by 4braincells** [comment]
I am scratching my head ;-D
So, one thing is: I was talking about "Custom property reference", so I should also have written CssMinifyTask instead of JsMinifyTask. My fault.

As I found a couple of deprecated stuff in my build.gradle, I upgraded gradle from 7.4.1 to 8.6 (step-wise :D),
then got the 2.0.0, but the result is again (or still)

```
> Task :cssMinifyBase
Warning: Custom property reference encountered. Please note that custom properties do not work with all major browsers, and their use is discouraged. at admin.css line 40:742
Warning: Custom property reference encountered. Please note that custom properties do not work with all major browsers, and their use is discouraged. at admin.css line 99:1678
Warning: Custom property reference encountered. Please note that custom properties do not work with all major browsers, and their use is discouraged. at admin.css line 122:2017
Warning: Custom property reference encountered. Please note that custom properties do not work with all major browsers, and their use is discouraged. at base.css line 22:320
```

Am I doing s.t.h wrong?

**Comment by 4braincells** [comment]
BTW, the gradle config is now:
```

import org.gradlewebtools.minify.CssMinifyTask
import org.gradlewebtools.minify.JsMinifyTask
minification {
    tasks.register('jsMinifyBase', JsMinifyTask) {
        srcDir = project.file("$projectDir/src/main/resources/static/js")
        dstDir = project.file("${layout.buildDirectory.get().asFile}/resources/main/static/js")
        print "Minifying JS to " + dstDir + "\n"
        options.ignoreMinFiles = true
    }
    tasks.register('cssMinifyBase', CssMinifyTask) {
        srcDir = project.file("$projectDir/src/main/resources/static/css")
        dstDir = project.file("${layout.buildDirectory.get().asFile}/resources/main/static/css")
        print "Minifying CSS to " + dstDir + "\n"
        options.ignoreMinFiles = true
    }
}

processResources {
    if (buildLevel == "RELEASE") {
        exclude "/static/css/*.css"
        exclude "/static/js/*.js"
        filesMatching(['/templates/*.html', '/templates/**/*.html']) {
            filter { line ->
                {
                    line = line.replaceAll('/css/base.css', '/css/base.min.css')
                            .replaceAll('/css/admin.css', '/css/admin.min.css')
                            .replaceAll('/js/apply.js', '/js/apply.min.js')
                            .replaceAll('/js/cancel.js', '/js/cancel.min.js')
                            .replaceAll('/js/admin.js', '/js/admin.min.js')
                }
            }
        }
        dependsOn(jsMinifyBase)
        dependsOn(cssMinifyBase)
    }
}
```
(I'm still on thymeleaf here)

**Comment by 616slayer616** [comment]
I thought the issue is with the JsMinifyTask as mentioned in the title.
But it is Really with the CSS task.
That uses another library.
Unfortunately, it is not maintained anymore by Google.
It would be nice to find a replacement.

In the meantime, I maintain a fork of this repo.
This could be the solution to the issue:
https://github.com/616slayer616/closure-stylesheets/pull/19

I will have to get the build working first though.

**Comment by 616slayer616** [comment]
https://github.com/gradle-webtools/gradle-minify-plugin/pull/51
