### ISSUE TITLE
Do not minimyze .min files

### ISSUE THREAD

**Issue by raccoon1515** [gradle-webtools/gradle-minify-plugin#8]
I think, that it would be great if the plugin will not try to minimize already minimized .min files in srcDir, and just copy them to dstDir.

**Comment by 616slayer616** [comment]
You mean in case further minification or a special operation from the closure compiler could  corrupt the already minified file?

I will have a look if I can do that.

**Comment by raccoon1515** [comment]
Yes, I suggest do not minimize files with suffix "_.min._". I believe that this files should be just copied as is to the destination directory.

**Comment by 616slayer616** [comment]
Oh I forgot the copying.
Will add that.

**Comment by 616slayer616** [comment]
I think this should achieve what we want:
https://github.com/gradle-webtools/gradle-minify-plugin/pull/9
